micronaut:
  application:
    name: ociFunctionAtpNativeImage
datasources:
  default:
    ocid: ocid1.autonomousdatabase.oc1.iad.abuwcljtvkdjhnkvwygavqgw3osg2cx4clehtrwkjy7xx5xzp4qwwwkaxzla
    walletPassword: micronaut.1
    username: mnocidemo
    password: "XXXXXXX"
